# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      - name: Checkout app repository
        uses: actions/checkout@v2
        with:
          repository: canhnguyenop/test-gittag
          ref: v0.0.1
          # push/commit Personal Access Token.
          token: ${{ secrets.ACTION_TOKEN }} # Change token
      
      - name: Get commitID from tag
        id: app-repo
        run: |
          ls -la
          echo $PWD
          HERA_RELEASE_VERSION=$(head -n 1 VERSION)
          echo HERA_RELEASE_VERSION=$HERA_RELEASE_VERSION
          VERSION=$(/usr/bin/git rev-list -n 1 $HERA_RELEASE_VERSION | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ steps.app-repo.outputs.version }}
          echo Add other actions to build,
          echo test, and deploy your project.
